/*DATA DEFINITION LANGUAGE~ 데티터 정의언어 : 객체를 생성 변경 삭제하는 구문. */
--CREATE ALTER DROP

--<ALTER> : 객체를 변경
--ALTER TABLE 테이블명 변경할 내용;

--변경할 내용 
--1)컬럼 추가/수정/삭 제
--1.컬럼추가(ADD) : ADD 컬럼명 자료형 디폴트 제약조건 
--DEPT_COPY에 CNAME 컬럼 추가
ALTER TABLE DEPT_COPY ADD CNAME VARCHAR(20);
SELECT * FROM DEPT_COPY;

ALTER TABLE DEPT_COPY ADD LNAME VARCHAR(20) DEFAULT '한국';

--2.컬럼수정(MODIFY)
-->자료형 수정  : MODIFY  컬럼명 바꾸고자하는 자료형
ALTER TABLE DEPT_COPY MODIFY DEPT_ID CHAR(3);
ALTER TABLE DEPT_COPY MODIFY DEPT_ID NUBMER;--안됨
ALTER TABLE DEPT_COPY MODIFY DEPT_TITLE VARCHAR(10);--이미 있는 데이터값이 설정한 크기보다 커서
-->DEFAULT 수정: MODIFY  컬럼명 DEFAULT 바꾸고자하는 기본값

--DEPT TITLE 컬럼을 VARCHAR2(50)
ALTER TABLE DEPT_COPY MODIFY DEPT_TITLE VARCHAR2(50);
--LOCATION_ID 컬럼을 VARCHAR2(4)
ALTER TABLE DEPT_COPY MODIFY LOCATION_ID VARCHAR2(4);
--LNAME 컬럼의 기본값을 '미국'으로 변경
ALTER TABLE DEPT_COPY MODIFY LNAME DEFAULT '미국';
--디폴트값 바꾼다해서 이전데이터값은 안바뀜
ALTER TABLE DEPT_COPY 
    MODIFY DEPT_TITLE VARCHAR2(50)
    MODIFY LOCATION_ID VARCHAR2(4)
    MODIFY LNAME DEFAULT '미국';
--3.컬럼삭제(DROP COLUMN) : DROP COLUMN 삭제하고자 하는 컬럼명
CREATE TABLE DEPT_COPY2
AS SELECT * FROM DEPT_COPY;

SELECT * FROM DEPT_COPY2;
--DEPT_COPY2로부터 DEPT_ID 칼럼지우기
ALTER TABLE DEPT_COPY2 DROP COLUMN DEPT_ID;
ALTER TABLE DEPT_COPY2 DROP COLUMN DEPT_TITLE;--다중삭제는 불가
ALTER TABLE DEPT_COPY2 DROP COLUMN CNAME;
ALTER TABLE DEPT_COPY2 DROP COLUMN LNAME;
ALTER TABLE DEPT_COPY2 DROP COLUMN LOCATION_ID;
--ORA-12983: cannot drop all columns in a table 최소한개 컬럼 있어야함.


--2)제약조건 추가/삭제 --> 수정은 불가(수정하고자한다면 삭제후 새로 추가)
--2-1 제약조건 추가
   -- PRIMARY KEY : ADD PRIMARY KEY(칼럼명)
   -- FOREIGN KEY : ADD FOREIGN KEY(칼럼명)  REFFERENCES 참조할테이블
   -- UNIQUE : ADD UNIQUE(칼러명)    
   -- CHECK : ADD CHEKCK(칼럼에대한 조건)
   -- NOT NUL : MODIFY  컬렴명  NULL|NOTNULL 
   -- 제약조건 지정하고자한다면 CONSTRAINT 설정하면됨
 
ALTER TABLE DEPT_COPY
    ADD CONSTRAINT DCOPY_PK PRIMARY KEY(DEPT_ID)
    ADD CONSTRAINT DCOPY_UQ UNIQUE(DEPT_TITLE)
    MODIFY LNAME CONSTRAINT DCOPY_NN NOT NULL;    

--2-2 제약 조건 삭제 : DROP CONSTRAINT 제약조건명
--NOT NULL은 삭제가 안되서 MODIFY 로 지워야함
ALTER TABLE DEPT_COPY DROP CONSTRAINT DCOPY_PK;

ALTER TABLE DEPT_COPY
    DROP CONSTRAINT DCOPY_UQ
    MODIFY LNAME NULL;
--3)컬럼명/테이블명 변경
--3-1 컬럼명 변경 : RENAME COLUMN 기존컬러명 TO 바꿀 컬럼명
ALTER TABLE DEPT_COPY RENAME COLUMN DEPT_TITLE TO DEPT_NAME;
--3-2 제약조건명 변경 : RENAME CONSTRAINT 
--SYS_C007194
ALTER TABLE DEPT_COPY RENAME CONSTRAINT SYS_C007194 TO DOCOPY_LID_NN;
--3-3 테이블명 변경 RENAME 기존테이블명 TO 바꿀테이블명
    ALTER TABLE DEPT_COPY RENAME TO DEPT_TEST;

------------------------------------------------------------------------

--<DROP> : 객체를 삭제

DROP TABLE DEPT_TEST;

--단 어딘가 참조되고있는 부모테이블은 삭제 잘안됨 
--삭제하고자 한다면
--방법1. 자식 테이블 먼저 삭제후 부모테일 삭제
--방법2. 그냥 부모테이블만 삭제하는데 제약조건까지 같이 삭제하는 방법 
--        DROP TABLE 테이블명 CASCADE CONSTRAINT




















