--1
SELECT DEPARTMENT_NAME AS "학과 명", CATEGORY AS "계열"
FROM TB_DEPARTMENT;

--2 국어국문학과 의 정원은 20 명입니다.
SELECT DEPARTMENT_NAME ||'의 정원은 '|| CAPACITY ||'명입니다.' AS "학과별 정원"
FROM TB_DEPARTMENT;

--3
SELECT STUDENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NO='001'
AND SUBSTR(STUDENT_SSN, 8, 1)IN ('2','4')
AND ABSENCE_YN = 'Y';

--4
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119');

--5
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT 
WHERE CAPACITY >=20 AND CAPACITY<=30;
--WHERE CAPACITY BETEEN 20AND 30;

--6
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--7
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

--8
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--9
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

--10
SELECT STUDENT_NO ,STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE TO_CHAR(ENTRANCE_DATE, 'YY/MM/DD') LIKE '02%'
AND STUDENT_ADDRESS LIKE '%전주%'
AND ABSENCE_YN = 'N';

--ADDITIONAL
--1
SELECT STUDENT_NO ,STUDENT_NAME, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 
FROM TB_STUDENT
WHERE DEPARTMENT_NO='002'
ORDER BY ENTRANCE_DATE ASC;

--2
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) ^=3;
--3

SELECT PROFESSOR_NAME, FLOOR(MONTHS_BETWEEN(SYSDATE, '19' || SUBSTR(PROFESSOR_SSN, 1, 6) ) / 12 )
FROM TB_PROFESSOR
ORDER BY FLOOR(MONTHS_BETWEEN(SYSDATE, '19' || SUBSTR(PROFESSOR_SSN, 1, 6) ) / 12 ) ASC;

--4
SELECT SUBSTR(PROFESSOR_NAME,2,2)
FROM TB_PROFESSOR;
--5
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE MONTHS_BETWEEN(ENTRANCE_DATE, TO_DATE('19'||SUBSTR(STUDENT_SSN,1,6),'YYYYMMDD'))/12 > 19.166;

--6
SELECT TO_CHAR(TO_DATE('2020-12-25','YYYY-MM-DD'),'DAY')
FROM DUAL; -- TO_CHAR(날짜 , 'DAY') 날짜를 요일 문자열로 바꿈.
--7
SELECT TO_CHAR(TO_DATE('99/10/11','YY/MM/DD'), 'YYYY-MM-DD'), TO_CHAR(TO_DATE('49/10/11','YY/MM/DD'), 'YYYY-MM-DD')
FROM DUAL;
SELECT TO_CHAR(TO_DATE('99/10/11','RR/MM/DD'), 'YYYY-MM-DD'), TO_CHAR(TO_DATE('49/10/11','RR/MM/DD'), 'YYYY-MM-DD')
FROM DUAL;

--8
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE NOT STUDENT_NO LIKE 'A%';

--9
SELECT ROUND(AVG(POINT),1) AS "평점"
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE STUDENT_NO = 'A517178';

--10
SELECT DEPARTMENT_NO, COUNT(STUDENT_NO)
FROM TB_STUDENT 
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--11
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12
SELECT DISTINCT(SUBSTR(TERM_NO,1,4)), ROUND(AVG(POINT),1)
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY SUBSTR(TERM_NO,1,4);

--13
SELECT DEPARTMENT_NO,COUNT(*)
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--14
SELECT A.STUDENT_NAME , COUNT(*)
FROM TB_STUDENT A, TB_STUDENT B
WHERE A.STUDENT_NAME= B.STUDENT_NAME 
AND A.STUDENT_NO^=B.STUDENT_NO
GROUP BY A.STUDENT_NAME
ORDER BY A.STUDENT_NAME;

--15

SELECT SUBSTR(TERM_NO,1,4)AS 년도,SUBSTR(TERM_NO,5,2)AS 학기 ,ROUND(AVG(POINT),1)AS 평점
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2)
UNION  
SELECT SUBSTR(TERM_NO,1,4)AS 년도, '' AS 학기, ROUND(AVG(POINT),1)AS 평점
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
UNION
SELECT '' AS 년도, '' AS 학기, ROUND(AVG(POINT),1) AS "평점"
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE STUDENT_NO = 'A112113'
ORDER BY 1, 2;

--3SELECT OPTION
--1
SELECT  STUDENT_NAME AS"학생이름", STUDENT_ADDRESS AS 주소지
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

--2
SELECT  STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN= 'Y'
ORDER BY STUDENT_SSN DESC;
--3
SELECT STUDENT_NAME, STUDENT_NO, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE NOT STUDENT_NO LIKE  'A%'
AND (STUDENT_ADDRESS LIKE '%강원도%'OR STUDENT_ADDRESS LIKE '%경기도%') 
ORDER BY STUDENT_NAME; 
--4
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NO='005'
ORDER BY PROFESSOR_SSN ASC;
--5

SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE TERM_NO = '200402'AND
CLASS_NO ='C3118100' 
ORDER BY POINT DESC;
--6
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY STUDENT_NAME DESC;

--7
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM  TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);

--8
SELECT CLASS_NAME, PROFESSOR_NAME
FROM  TB_CLASS
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO);

--9
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT D USING(DEPARTMENT_NO)
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO)
WHERE D.CATEGORY = '인문사회';
--10
SELECT  STUDENT_NO AS 학번,STUDENT_NAME AS 학생이름 ,ROUND(SUM(POINT)/COUNT(STUDENT_NO),1)AS 전체평점
FROM TB_STUDENT
JOIN TB_DEPARTMENT D USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NO='059'
GROUP BY STUDENT_NO,STUDENT_NAME ;

--11
SELECT DEPARTMENT_NAME, STUDENT_NAME, PROFESSOR_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT D USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

--12

SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_CLASS USING (CLASS_NO)
WHERE SUBSTR(TERM_NO,1,4)='2007'
AND CLASS_NO = 'C2604100';

--13
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
LEFT JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
WHERE DEPARTMENT_NO IN ('056','057','058','059','060','061','062','063')--비트윈문?
AND PROFESSOR_NO IS NULL
ORDER BY DEPARTMENT_NAME;

--14 
SELECT STUDENT_NAME AS 학생이름, NVL(P.PROFESSOR_NAME, '지도교수 미지정') AS 지도교수
FROM TB_STUDENT S
LEFT JOIN TB_PROFESSOR P ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE S.DEPARTMENT_NO = '020';

--15
SELECT STUDENT_NO, STUDENT_NAME,DEPARTMENT_NAME, SUM(POINT)/COUNT(STUDENT_NO)
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE ABSENCE_YN = 'N' 
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING (SUM(POINT) / COUNT(STUDENT_NO)) >= 4.0;

--16
SELECT CLASS_NO, CLASS_NAME, TRUNC(AVG(POINT),8)
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(CLASS_NO)
WHERE DEPARTMENT_NO='034' 
AND CLASS_TYPE LIKE '%전공%'
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY CLASS_NO;

--17
--최경희는 무슨과?
SELECT DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE STUDENT_NO='A513110';

--메인
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME=(SELECT DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE STUDENT_NO='A513110'); 

--18~ ROWNUM 문제구나
SELECT STUDENT_NO, STUDENT_NAME, AVG(POINT)
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NAME='국어국문학과'
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY AVG(POINT) DESC; 

SELECT *
FROM (SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NAME='국어국문학과'
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY AVG(POINT) DESC )
WHERE ROWNUM=1;

--19 DEPARTMENT_NO='034' 환경조경학과가 속한 같은계열의 학과의 

--1.환경조성학과의 계열은?
SELECT CATEGORY
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NO='034';

--2.환경조경학과가 속한 같은 계열학과들 환경포함
SELECT DEPARTMENT_NAME
FROM TB_DEPARTMENT
WHERE CATEGORY=(SELECT CATEGORY
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NO='034');

--3.학과별 전공과목 평점? ROUND(AVG(POINT),1)
SELECT DEPARTMENT_NAME, ROUND(AVG(POINT),1)
FROM TB_DEPARTMENT
JOIN TB_CLASS USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(CLASS_NO)
WHERE CATEGORY=(SELECT CATEGORY
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NO='034')
AND CLASS_TYPE LIKE '%전공%'
GROUP BY DEPARTMENT_NAME;
--그룹화후 , CLASS 조인 ,GRADE 조인 , 전공만
COMMIT;
-----------------------------------------------------------
--DDL
--1, 3
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10) CONSTRAINT NAME_PK PRIMARY KEY,
    USE_YN CHAR(1) DEFAULT 'Y'
);

--2, 4
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10) CONSTRAINT NAME_NN NOT NULL
);

--5 크기만 변경하는 작업은 ALTER TABLE ... MODIFY 문
ALTER TABLE TB_CLASS_TYPE
MODIFY NO VARCHAR2(10);

ALTER TABLE TB_CLASS_TYPE
MODIFY NAME VARCHAR2(20);

ALTER TABLE TB_CATEGORY 
MODIFY NAME VARCHAR2(20);

