--1
SELECT EMP_NO, EMP_NAME, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN JOB USING (JOB_CODE)
WHERE SUBSTR(EMP_NO, 1,1)= '7' AND 
SUBSTR(EMP_NO, 8, 1) IN ('2', '4')
AND EMP_NAME LIKE '전%';--70년대생이면서 여자인  

--2
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, CEIL(FLOOR(MONTHS_BETWEEN(SYSDATE,SUBSTR(EMP_NO, 1, 6)))/12)
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN JOB USING (JOB_CODE)
WHERE CEIL(FLOOR(MONTHS_BETWEEN(SYSDATE,SUBSTR(EMP_NO, 1, 6)))/12) = ( SELECT MIN(CEIL(FLOOR(MONTHS_BETWEEN(SYSDATE, SUBSTR(EMP_NO, 1, 6))) / 12))
                                                                       FROM EMPLOYEE);
--3
SELECT EMP_ID, EMP_NAME, JOB_NAME
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE EMP_NAME LIKE '%형%';

--4
SELECT EMP_NAME, JOB_NAME, DEPT_CODE,DEPT_TITLE
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN JOB USING (JOB_CODE)
WHERE DEPT_CODE IN ('D5','D6')
ORDER BY DEPT_CODE DESC, JOB_CODE DESC;

--5
SELECT EMP_NAME, BONUS, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE)
WHERE BONUS IS NOT NULL;

--6
SELECT EMP_NAME, JOB_NAME, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE);


--7
SELECT EMP_NAME, DEPT_TITLE, LOCAL_NAME, NATIONAL_NAME
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE)
JOIN NATIONAL USING(NATIONAL_CODE)
WHERE NATIONAL_NAME IN ('한국','일본');


--8
--같은사원 조회하기
SELECT EMP_NAME, DEPT_CODE
FROM EMPLOYEE E 
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID);


SELECT  E.EMP_NAME, E.DEPT_CODE, S.EMP_NAME
FROM  EMPLOYEE E, EMPLOYEE S
WHERE S.DEPT_CODE = E.DEPT_CODE
AND S.EMP_NAME ^= E.EMP_NAME
ORDER BY E.EMP_NAME;

--9
SELECT EMP_NAME, JOB_NAME, SALARY 
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
WHERE JOB_CODE IN ('J4', 'J7')
AND BONUS IS NULL;

--> NVL 이용해서?

SELECT EMP_NAME, JOB_NAME, SALARY,  NVL(BONUS, 0)
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
WHERE JOB_CODE IN ('J4', 'J7')
AND NVL(BONUS, 0)=0;


